language: node_js
node_js: "4.1"
before_install:
    - npm install -g typescript@next typings webpack nodeunit coveralls jscoverage
branches:
    only:
        - typescript
install: make prepare
script:
    - make
    - make test
after_script:
    - jscoverage src/mth/build/tests/main.js && nodeunit --reporter=lcov src/mth/build/tests/main-cov.js| coveralls
notifications:
    on_failure: always
    on_success: never
