language: node_js
node_js: "4.1"
before_install:
    - npm install -g typescript@next tsd webpack
branches:
    only:
        - typescript
install: make prepare
script: make
notifications:
    on_failure: always
    on_success: never
